### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by mrboni** [mturnshek/nn_psychadelics#1]
I want to play!   Can you give me a nudge in the right direction?

**Comment by mturnshek** [comment]
Unfortunately, I'm preoccupied and can't take the time right now to give you a nudge on this particular repo.

Take a look at the following repo which has a much more robust implementation of this type of idea. You'll get different (and much more practical) results than you would from using supervised learning, which is what `nn_psychadelics` uses, since the following repo uses a GAN frame predictor.
https://github.com/dyelax/Adversarial_Video_Generation

**Comment by mrboni** [comment]
I will do, thanks.

Your naming convention appealed, thassall :)

**Comment by mturnshek** [comment]
If you want to shoot me an email at matthewturnshek at gmail dot com, I have a couple videos I can share with you for a little peek of `nn_psychadelics` when I had the environment and a dataset up and running.
